### ISSUE TITLE
check_mem_region doesn't exist in Kernel 4

### ISSUE THREAD

**Issue by NTICompass** [yeradis/crystalhd#2]
I was trying to compile this on kernel 4.1 with gcc 4.9 and got the following error:

```
/home/nticompass/Code/crystalhd/driver/linux/crystalhd_lnx.c: In function ‘chd_pci_reserve_mem’:
/home/nticompass/Code/crystalhd/driver/linux/crystalhd_lnx.c:541:2: error: implicit declaration of function ‘check_mem_region’ [-Werror=implicit-function-declaration]
  rc = check_mem_region(bar0, i2o_len);
  ^
```

I know nothing about C, nor about writing Linux drivers, but would just removing the call to `check_mem_region` fix it, or is more work required?

**Comment by dbason** [comment]
@NTICompass I'm in the same boat as you but from a bit of research I think it's OK to comment out the if block that references that.  It was removed from the kernel because it was racy - between checking the memory and doing the ioremap something else could have grabbed it.

For full correctness it should probably be changed to request_mem_region before the iomap - I'll try and do a PR for this tomorrow, but it should work without it.

**Comment by NTICompass** [comment]
I figured I'd try to test this out on my own.  I commented out the `check_mem_region` calls, which let it actually compile!  I then launched `vlc --codec crystalhd video.mp4` and `mpv` (I forget the full mpv command right now, but it used `--vo`) and it works! :-)

**Comment by Ardakilic** [comment]
Just out of curiousity, how do you identify the driver running? I've compiled successfully, but in dmesg output there's no message that CrystalHD started decoding. Do I have to compile VLC myself?

Using ubuntu 14.04 x64.

**Comment by NTICompass** [comment]
I'm running Debian 8, and I see in `dmesg` that the driver is loaded on boot and running when I use mpv or vlc.  I installed those from http://deb-multimedia.org, so they may be different build from what's in Debain's default repo.  I don't know what's in Ubuntu's repo or if http://deb-multimedia.org will work with Ubuntu.

I don't remember the exact steps I used to install the driver, but I know I see messages in `dmesg`.  I *did* take notes about the install process and when I get home and get my notebook, I can explain my process.

**Comment by Ardakilic** [comment]
@NTICompass Thank you! I'm waiting for your reply then. One of the reasons I'm sticking with Ubuntu LTS is that I couldn't compile the driver on Debian 8.

The thing is that, the driver is installed and loaded, but with the old driver, it used to announce it's decoding, but I can't see it so I'm not sure if it's actually running. I can see driver is loaded, but I am not sure whether it's decoding.

**Comment by NTICompass** [comment]
I do have kernel 4.1 (and I think gcc-4.9) installed from jessie-backports.  The stable (non-backports) kernel didn't work with my machine's video card.  When I get back home, I'll see what I have written in my notebook about how I installed it.

Maybe I'll even fork this repo and hack up my own README, I'll see.

**Comment by dbason** [comment]
Instillation instructions are in the readme of the repo.  It's a kernel module so you can check it's loaded by lsmod | grep crystalhd.  There is a user space library too - libcrystalhd - which applications will need to use the kernel module.

**Comment by dbason** [comment]
@NTICompass I'm getting a compilation error in crystalhd_cmds.c: comparison of constant 2 with boolean expression is always false - did you see this when you compiled?

**Comment by NTICompass** [comment]
@Ardakilic: Besides the driver and libcrystalhd, you also need the firmware installed (`apt-get install firmware-crystalhd` should do it).

**Comment by NTICompass** [comment]
@dbason: I'll try to test that tomorrow or Friday when I get a chance.

**Comment by Ardakilic** [comment]
@NTICompass Thank you! Indeed I didn't install `firmware-crystalhd` in addition to drivers. I'll check this evening :) I'll let you guys know.

**Comment by dbason** [comment]
@NTICompass the changes I've made should work on gcc 4.9, but I haven't fixed gcc 5.1 issues yet.  I can compile that file but because I've only got gcc 5.1 I can't compile the rest and check the driver actually works.  If you can compile it with 4.9 and check it runs OK that would be awesome.

**Comment by dbason** [comment]
Actually don't worry, it compiles but throws errors on load.  Need to do more debugging

**Comment by dlenski** [comment]
@dbason, your fork is working very well for me on Xubuntu 16.04 with kernel 4.4.0. It's great to be able to play 1080p video on an old Atom Nettop :+1:.

**Comment by dbason** [comment]
Awesome to hear!

**Comment by Ardakilic** [comment]
Very late catch-up:

@dbason 's fork compiled successfully on Lubuntu 16.04 with 4.4.x kernel, and I can use BCM70015 along with VLC and Gnome Mplayer successfully. Shame that Kodi and Plex removed support on recent versions.
